### ISSUE TITLE
Overall Unofficial Roadmap

### ISSUE THREAD

**Issue by joshgoebel** [wren-lang/wren-cli#98]
I was speaking with Ruby and this list was entirely off the cuff but I thought I'd include it here and we can update it over time and turn it into more of an actual plan:

- [ ] get the input stuff sorted out so it's not painful to use the repl (#71, #72 needs testing)
- [ ] make sure `Stdin`/`Stdout` etc is good (#56, #59, #55, #27, #29, #17)
- [ ] `File` / `Directory` / `IO` rounded out (#84)
- [ ] child process stuff done properly (including std redirections etc) (I've started on this with #94 but no redirection support)
- [ ] basic networking (tcp)
- [ ] higher level networking (http etc)

**Comment by clsource** [comment]
Is there really a need for basic networking? My opinion is that component can be externalized via extensions.
In my opinon a higher priority than networking would be extensability via plugins or dynamic libs 👍

**Comment by joshgoebel** [comment]
This was before the discussion happening in #93.  So perhaps it should be understood as a list of "what should CLI be capable of doing" rather than "what all is built in"... though I think all the other stuff is good (and most of it's there already save process handling).

This is still a good rough draft 0.1 list whether networking is in or out of scope though. :-)   Can't do much without networking these days. :)

**Comment by PureFox48** [comment]
> Can’t do much without networking these days. :)

Very true and personally I think there should be some networking support in the CLI’s standard modules even if it’s fairly basic.
